
spring:
  kafka:
    consumer:
      bootstrap-servers: 0.0.0.0:9092
      group-id: drone
      client-id: drone-consumer
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: 0.0.0.0:9092
      client-id: email-producer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  name:
    consumer: drone-data
    producer: send-email