spring:
  kafka:
    consumer:
      bootstrap-servers: 0.0.0.0:9092
      group-id: email
      client-id: email-consumer
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: GMAIL_SERVER_USERNAME
    password: GMAIL_SERVER_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

topic:
  name:
    consumer: send-email

email:
  to: alex_maiabr@hotmail.com