server:
  port: 8080

# commons
auto:
  create:
    topics:
      enable: true

spring:
  kafka:
    producer:
      bootstrap-servers: 0.0.0.0:29092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: drones

topic:
  name:
    producer: drone-read

