server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: 0.0.0.0:9092
      client-id: drone-producer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": drone:br.com.fiap.droneproducer.model.Drone

topic:
  name:
    producer: drone-data

