server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: 0.0.0.0:9092
      client-id: drone-producer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /api-docs

topic:
  name:
    producer: drone-data
  partition:
    number: 1